<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Смутные Времена - браузерная онлайн игра</title>
	<link rel='stylesheet' href='/styles/main.css' type='text/css' />
	<script type='text/javascript' src='https://code.jquery.com/jquery-3.5.1.min.js'
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>
{content}
</body>
</html>