<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Смутные Времена - браузерная онлайн игра</title>
	<link rel='stylesheet' type='text/css' href='/styles/main.css' />
	<link rel='stylesheet' type='text/css' href='/styles/toastr.css' />
	<script type='text/javascript' src='https://code.jquery.com/jquery-3.5.1.min.js'
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script type='text/javascript' src='/js/toastr/toastr.js'></script>
</head>

<style>
	//body {background-color: #ddedfb;}
	body table {
		margin-top: 15px;
		margin-left: 10px;
	}	
	body table td {
		vertical-align: top;
	}	
	img#logo {
		width: 750px;
	}
	div#statistic {
		margin-top: 50px;
		margin-left: 20px;
	}
	div#total-count {
		margin-bottom: 25px;
	}
</style>

<body>
    <table cellspacing="30">
		<tr>
			<td><img id="logo" src="/images/DarkAges.jpg"/></td>
			<td>
				<form id="loginForm" action='#'>
					<table>
						<tr><td>Имя:</td><td><input type="text" name="login"></td></tr>
						<tr><td>Пароль:</td><td><input type="password" name="password"></td></tr>
						<tr><td></td><td align="right">
							<button type='submit'>Вход</button>
							<a href='/vr/registration/'><button type='button'>Регистрация</button></a>
						</td></tr>
					</table>
				</form>
				<div id="statistic">
					<div id="online-count">Онлайн: 0</div>
					<div id="total-count">Зарегистрировано: <?= count($users) ?></div>
					<div>
						<? foreach ($users as $person) { ?>
							<div>
								<?= $person['p_login'] ?> [<?= $person['p_level'] ?>]
								<?= $person['p_race'] == 1 ? 'Орк' : ($person['p_race'] == 2 ? 'Человек' : 'Эльф') ?>
								(<?= $person['p_experience'] ?>)
							</div>
						<? } ?>
					</div>
					<center id="www-counters">
						<!-- Rating Mail.ru counter -->
						<script type="text/javascript">
							var _tmr = window._tmr || (window._tmr = []);
							_tmr.push({id: "3183687", type: "pageView", start: (new Date()).getTime()});
							(function (d, w, id) {
							  if (d.getElementById(id)) return;
							  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
							  ts.id = id;
							  ts.src = "https://top-fwz1.mail.ru/js/code.js";
							  var f = function () {var s = d.getElementsByTagName("script")[0];
							  s.parentNode.insertBefore(ts, s);};
							  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); }
							  else { f(); }
							})(document, window, "topmailru-code");
						</script><noscript><div>
							<img src="https://top-fwz1.mail.ru/counter?id=3183687;js=na"
								style="border:0;position:absolute;left:-9999px;" alt="Top.Mail.Ru" />
						</div></noscript>
						<!-- //Rating Mail.ru counter -->
						<!-- Rating Mail.ru logo -->
						<a href="https://top.mail.ru/jump?from=3183687">
							<img src="https://top-fwz1.mail.ru/counter?id=3183687;t=610;l=1" style="border:0;"
								height="40" width="88" alt="Top.Mail.Ru" /></a>
						<!-- //Rating Mail.ru logo -->
						
						<!-- Top100 (Kraken) Widget -->
						<span id="top100_widget"></span>
						<!-- END Top100 (Kraken) Widget -->

						<!-- Top100 (Kraken) Counter -->
						<script>
							(function (w, d, c) {
							(w[c] = w[c] || []).push(function() {
								var options = {
									project: 7115933,
									element: 'top100_widget',
								};
								try {
									w.top100Counter = new top100(options);
								} catch(e) { }
							});
							var n = d.getElementsByTagName("script")[0],
							s = d.createElement("script"),
							f = function () { n.parentNode.insertBefore(s, n); };
							s.type = "text/javascript";
							s.async = true;
							s.src =
							(d.location.protocol == "https:" ? "https:" : "http:") +
							"//st.top100.ru/top100/top100.js";

							if (w.opera == "[object Opera]") {
							d.addEventListener("DOMContentLoaded", f, false);
						} else { f(); }
						})(window, document, "_top100q");
						</script>
						<noscript>
						  <img src="//counter.rambler.ru/top100.cnt?pid=7115933" alt="Топ-100" />
						</noscript>
						<!-- END Top100 (Kraken) Counter -->
					</center>
				</div>
			</td>
		</tr>
	</table>	
</body>
</html>